### ISSUE TITLE
Difference image query linking to many broken files

### ISSUE THREAD

**Issue by nrgolovich** [MickaelRigault/ztfquery#22]
I'm querying for difference images with a simple search for files near an ra/dec point between two times. The majority of the files in my zquery.metatable do not download, and the linked files do not exist on the server. 

`zquery.load_metadata(radec=[182.43061649701434,-1.0493840126477587], 
                 size=15, 
                 sql_query="obsjd>2458447.25 and obsjd<2458448.25")`

Only 3/53 files download with the above query.

**Comment by simeonreusch** [comment]
Have you ruled out an authorization issue?

**Comment by nrgolovich** [comment]
All of the 53 have ipac_gid==1. I have gathered that means they are public data. Is this what you meant?

**Comment by simeonreusch** [comment]
Unfortunately, public can also be mean "is in principle public, but only published in 1-year intervals". Therefore the 2019 MSIP data is not accessible yet.

**Comment by fmasci** [comment]
MSIP data taken up to Jun 30, 2019 was made public about 1 month ago (DR2). The next release (DR3 in June 2020) will include data taken up to Dec 31, 2019.

Regards, Frank
________________________________

**Comment by nrgolovich** [comment]
The data I am after was taken in Nov 2018 - Feb 2019, so that shouldn't be it then.

**Comment by MickaelRigault** [comment]
Hi Nate,

Indeed, many imagine difference files you want do not exist. 

@fmasci: 
For the `sci/2018/1121/478484/` , why does the `scimrefdiffimg` exist for `zr_c15_o_q4` and not for `zr_c11_o_q4` ? (so CCD 15 ok, but not CCD 11)

**Comment by fmasci** [comment]
Both those quadrants do not have subtractions because their reference images were created on 2018-11-27 (6 days later). Here are the subtractions that exist for this exposure, simply because a production quality reference existed:

ztf_20181121478484_000471_zr_c01_o_q1_scimrefdiffimg.fits.fz
ztf_20181121478484_000471_zr_c01_o_q4_scimrefdiffimg.fits.fz
ztf_20181121478484_000471_zr_c12_o_q2_scimrefdiffimg.fits.fz
ztf_20181121478484_000471_zr_c13_o_q1_scimrefdiffimg.fits.fz
ztf_20181121478484_000471_zr_c13_o_q2_scimrefdiffimg.fits.fz
ztf_20181121478484_000471_zr_c13_o_q4_scimrefdiffimg.fits.fz
ztf_20181121478484_000471_zr_c14_o_q1_scimrefdiffimg.fits.fz
ztf_20181121478484_000471_zr_c14_o_q2_scimrefdiffimg.fits.fz
ztf_20181121478484_000471_zr_c15_o_q1_scimrefdiffimg.fits.fz
ztf_20181121478484_000471_zr_c15_o_q2_scimrefdiffimg.fits.fz
ztf_20181121478484_000471_zr_c15_o_q3_scimrefdiffimg.fits.fz
ztf_20181121478484_000471_zr_c16_o_q1_scimrefdiffimg.fits.fz
ztf_20181121478484_000471_zr_c16_o_q2_scimrefdiffimg.fits.fz

Note: we plan to backfill all subtractions for which no reference existed during realtime processing. Stay tuned.

Regards, Frank

On Jan 20, 2020, at 1:23 AM, Mickael Rigault <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Nate,

Indeed, many imagine difference files you want do not exist.

@fmasci<https://github.com/fmasci>:
For the sci/2018/1121/478484/ , why does the scimrefdiffimg exist for zr_c15_o_q4 and not for zr_c11_o_q4 ? (so CCD 15 ok, but not CCD 11)

**Comment by nrgolovich** [comment]
Great, thanks for the information. I guess I'll proceed with my analysis of the data I can get now and check back later.
